Readthedocs import extension error (#537)
Readthedocs fails and is blocking existing PRs. Failure is: `Extension
error: Could not import extension sphinx_tabs.tabs (exception: cannot
import name 'TypeAliasType' from 'typing_extensions')`. The issue came
from pydantic==2.6.4 and typing_extensions==4.5.0. Sphinx uses Open AI
which requires "pydantic>=1.9.0, <3", "typing-extensions>=4.7, <5". The
versions have been changed in the readthedocs `yaml` file.

[ reviewed by @al-rigazzi ]
[ committed by @amandarichardsonn ]